imports:
  - path: pyproject.toml
    as: project
  - path: ../common.build.yml
    as: common

vars:
  version: $(${common.get_version} ${PROJECT_DIR}) 
  package_name: $(echo ${project.name} | tr '-' '_')
  build_dir: ${PROJECT_DIR}/${package_name}
  dist_dir: ${PROJECT_DIR}/dist


files-groups:
  source-files:
    - ${PROJECT_DIR}/src/**/*.py
    - ${PROJECT_DIR}/pyproject.toml
    - ${PROJECT_DIR}/src/**/*.json
    - ${PROJECT_DIR}/src/**/*.xml


rules:
  build:
    tags:
      - build
    required-files: source-files
    expected-files:
      - ${dist_dir}/${package_name}-${version}.tar.gz
      - ${dist_dir}/${package_name}-${version}-py3-none-any.whl
    commands:
      - cp -r ${PROJECT_DIR}/src ${build_dir}
      - ${common.create_metadata} ${build_dir} -v ${version} -p ${PROJECT_DIR}/pyproject.toml
      - MSM_VERSION=${version} ${PYTHON} -m build --wheel --sdist --outdir ${dist_dir} ${PROJECT_DIR}
      - rm -rf ${build_dir}

  # install-editable:
  #   tags:
  #     - dev-setup
  #   required-files: source-files
  #   commands:
  #     - $(PYTHON) -m pip install -e ${PROJECT_DIR}

  # install:
  #   tags:
  #     - setup
  #   required-files:
  #     - dist/${package_name}-${version}.py3-none-any.whl
  #   commands:
  #     - $(PYTHON) -m pip install dist/${package_name}-${version}.py3-none-any.whl

  # tests:
  #   tags:
  #     - test
  #   required-files: source-files
  #   commands:
  #     - $(PYTHON) -m unittest discover -s tests