name: On Pull Request
on:
  pull_request:
    branches:
      - "WORKFLOW_DISABLED"  # Change this to the branch you want to test pull requests against

permissions:
  contents: read
  actions: read

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13"]

    steps:

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Fetch all history for all tags

    - name: install make
      run: sudo apt-get install -y make

    - name: setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build pytest

    - name: setup nodejs
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: install nodejs dependencies
      run: npm install --global sass typescript

    - name: build
      run: make tests VERSION=${{ github.ref_name }}

    - name: publish test report
      if: success() || failure()
      uses: mikepenz/action-junit-report@v5
      with:
        report_paths: 'test-report.xml'
        include_passed: true

    - name: upload tests server logs
      if: success() || failure()
      uses: actions/upload-artifact@v4
      with:
        name: tests-server-logs
        path: tests/end-to-end/temp/
